apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Universal Base Image
  name: ubi8
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run Python 2.7 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-python-container/blob/master/2.7/README.md.
      iconClass: fab fa-redhat
      openshift.io/display-name: Python 2.7
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/django-ex.git
      supports: python:2.7,python
      tags: builder,python,hidden
      version: "2.7"
    from:
      kind: DockerImage
      name: registry.redhat.io/ubi8:8.4
    importPolicy:
      scheduled: true
    name: "8.4"
    referencePolicy:
      type: Local
  - annotations:
      description: |-
        Build and run Python applications on UBI. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-python-container/blob/master/3.8/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of Python available on OpenShift, including major version updates.
      iconClass: fab fa-redhat
      openshift.io/display-name: Python (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/django-ex.git
      supports: python
      tags: builder,python
    from:
      kind: ImageStreamTag
      name: 8.4
    name: latest
    referencePolicy:
      type: Local
