apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-pusher-anon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-pusher
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:unauthenticated
